import mongoose, { Schema, Document } from 'mongoose';

export interface ISetting extends Document {
  collegeName: string;
  collegeAddress: string;
  collegeLogoUrl?: string;
  certificateTitle: string;
  certificateStatement: string;
  certificatePrefix: string;
  academicYear?: string;
  signatoryName: string;
  signatoryDesignation: string;
  footerText: string;
  eligibleBatches: string[];
  eligibleYears: string[];
  updatedAt: Date;
}

const SettingSchema: Schema = new Schema(
  {
    collegeName: { type: String, default: 'MALNAD COLLEGE OF ENGINEERING' },
    collegeAddress: { type: String, default: 'Autonomous Institution Affiliated to VTU, Belagavi | Hassan, Karnataka - 573202' },
    collegeLogoUrl: { type: String, default: '' },
    certificateTitle: { type: String, default: 'NO DUE CERTIFICATE' },
    certificateStatement: {
      type: String,
      default: 'has cleared all outstanding financial dues, library books, laboratory equipment, hostel fees, and departmental obligations with the institution.'
    },
    certificatePrefix: { type: String, default: 'NDC/MCE/' },
    academicYear: { type: String, default: '2025-2026' },
    signatoryName: { type: String, default: 'Dr. K. S. Ananth' },
    signatoryDesignation: { type: String, default: 'Dean & Administrative Officer' },
    footerText: { type: String, default: 'This certificate is generated by the Autonomous No Due Clearance System.' },
    eligibleBatches: { type: [String], default: ['2022-2026', '2023-2027', '2024-2028', '2021-2025'] },
    eligibleYears: { type: [String], default: ['4th Year', 'Final Year', '3rd Year'] }
  },
  { timestamps: true }
);

export default mongoose.model<ISetting>('Setting', SettingSchema);
