import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import prisma from '../config/prisma';

export interface ClearanceItemPdf {
  departmentName: string;
  departmentCode: string;
  status: string;
  approvalTimestamp?: Date | string;
  reviewedByName?: string;
}

export class PdfService {
  public static async generateCertificatePdf(
    certificateData: {
      certificateNumber: string;
      studentName: string;
      usn: string;
      departmentName: string;
      batch: string;
      academicYear: string;
      issuedAt: Date;
      hodName?: string;
      clearances?: ClearanceItemPdf[];
    },
    outputPath: string
  ): Promise<string> {
    return new Promise(async (resolve, reject) => {
      try {
        const dir = path.dirname(outputPath);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }

        const settings = (await prisma.setting.findFirst()) || {
          collegeName: 'MALNAD COLLEGE OF ENGINEERING',
          collegeAddress: 'Autonomous Institution Affiliated to VTU, Belagavi | Hassan, Karnataka - 573202',
          certificateTitle: 'NO DUE CERTIFICATE',
          certificateStatement:
            'This is to officially certify that the student named below has cleared all institutional liabilities, returned all library books & laboratory equipment, settled all mess/hostel dues, and fulfilled all departmental clearance requirements with zero outstanding dues.',
          signatoryName: 'Dr. K. S. Ananth',
          signatoryDesignation: 'Dean & Administrative Officer',
          footerText: 'This certificate is generated by the Autonomous No Due Clearance System.'
        };

        const doc = new PDFDocument({
          size: 'A4', // 595.28 x 841.89
          margin: 0
        });

        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);

        const pageW = doc.page.width;  // 595.28
        const pageH = doc.page.height; // 841.89

        // 1. Luxury Double Outer Border (Navy & Gold with Soft Corners)
        doc
          .roundedRect(18, 18, pageW - 36, pageH - 36, 12)
          .lineWidth(2)
          .strokeColor('#1e3a8a')
          .stroke();

        doc
          .roundedRect(23, 23, pageW - 46, pageH - 46, 9)
          .lineWidth(1)
          .strokeColor('#d97706')
          .stroke();

        doc
          .roundedRect(27, 27, pageW - 54, pageH - 54, 7)
          .lineWidth(0.5)
          .strokeColor('#93c5fd')
          .stroke();

        // Corner Corner Brackets
        const cornerSize = 14;
        // Top Left
        doc.moveTo(32, 32 + cornerSize).lineTo(32, 32).lineTo(32 + cornerSize, 32).lineWidth(1.5).strokeColor('#d97706').stroke();
        // Top Right
        doc.moveTo(pageW - 32 - cornerSize, 32).lineTo(pageW - 32, 32).lineTo(pageW - 32, 32 + cornerSize).lineWidth(1.5).strokeColor('#d97706').stroke();
        // Bottom Left
        doc.moveTo(32, pageH - 32 - cornerSize).lineTo(32, pageH - 32).lineTo(32 + cornerSize, pageH - 32).lineWidth(1.5).strokeColor('#d97706').stroke();
        // Bottom Right
        doc.moveTo(pageW - 32 - cornerSize, pageH - 32).lineTo(pageW - 32, pageH - 32).lineTo(pageW - 32, pageH - 32 - cornerSize).lineWidth(1.5).strokeColor('#d97706').stroke();

        // 2. Official College Logo Emblem (Left side of header)
        const logoPath = path.resolve(process.cwd(), 'assets/mce_logo.png');
        const hasLogo = fs.existsSync(logoPath);
        if (hasLogo) {
          doc.image(logoPath, 38, 36, { width: 56, height: 56 });
        }

        doc
          .font('Helvetica-Bold')
          .fontSize(16)
          .fillColor('#1e3a8a')
          .text(settings.collegeName.toUpperCase(), 40, 38, {
            width: pageW - 80,
            align: 'center'
          });

        doc
          .font('Helvetica-Bold')
          .fontSize(8.5)
          .fillColor('#334155')
          .text('An Autonomous Institution Affiliated to Visvesvaraya Technological University, Belagavi', 40, 60, {
            width: pageW - 80,
            align: 'center'
          });

        doc
          .font('Helvetica')
          .fontSize(8)
          .fillColor('#64748b')
          .text('Approved by AICTE, New Delhi | Post Box No. 21, Hassan, Karnataka - 573202, India', 40, 74, {
            width: pageW - 80,
            align: 'center'
          });

        // Elegant Gold/Navy Divider
        doc
          .moveTo(42, 98)
          .lineTo(pageW - 42, 98)
          .lineWidth(1)
          .strokeColor('#e2e8f0')
          .stroke();

        doc
          .moveTo(pageW / 2 - 45, 98)
          .lineTo(pageW / 2 + 45, 98)
          .lineWidth(2)
          .strokeColor('#d97706')
          .stroke();

        // 3. Certificate Title Badge (Soft Rounded Corners)
        const titleBadgeW = 240;
        const titleBadgeH = 26;
        const titleBadgeX = (pageW - titleBadgeW) / 2;
        const titleBadgeY = 108;

        doc
          .roundedRect(titleBadgeX, titleBadgeY, titleBadgeW, titleBadgeH, 8)
          .fillAndStroke('#1e3a8a', '#1e3a8a');

        doc
          .font('Helvetica-Bold')
          .fontSize(12)
          .fillColor('#ffffff')
          .text('NO DUE CERTIFICATE', titleBadgeX, titleBadgeY + 7, {
            width: titleBadgeW,
            align: 'center'
          });

        // Certificate Number Sub-bar
        doc
          .font('Helvetica-Bold')
          .fontSize(9)
          .fillColor('#1e3a8a')
          .text(`Certificate Ref: ${certificateData.certificateNumber}`, 40, 142, {
            width: pageW - 80,
            align: 'center'
          });

        // 4. Student Master Details Card (Soft Rounded Corners)
        const metaBoxX = 45;
        const metaBoxY = 162;
        const metaBoxW = pageW - 90;
        const metaBoxH = 88;

        doc
          .roundedRect(metaBoxX, metaBoxY, metaBoxW, metaBoxH, 10)
          .fillAndStroke('#f8fafc', '#cbd5e1');

        // Left Column
        const c1X = metaBoxX + 16;
        doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('STUDENT FULL NAME', c1X, metaBoxY + 12);
        doc.font('Helvetica-Bold').fontSize(13).fillColor('#0f172a').text(certificateData.studentName.toUpperCase(), c1X, metaBoxY + 23);

        doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('UNIVERSITY SEAT NUMBER (USN)', c1X, metaBoxY + 48);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#1d4ed8').text(certificateData.usn, c1X, metaBoxY + 59);

        // Right Column
        const c2X = metaBoxX + 270;
        doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('ACADEMIC DEPARTMENT', c2X, metaBoxY + 12);
        doc.font('Helvetica-Bold').fontSize(10.5).fillColor('#0f172a').text(certificateData.departmentName, c2X, metaBoxY + 23, { width: 200 });

        const acadStr = certificateData.academicYear ? ` (${certificateData.academicYear})` : '';
        doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('BATCH / ACADEMIC YEAR', c2X, metaBoxY + 48);
        doc.font('Helvetica-Bold').fontSize(10.5).fillColor('#0f172a').text(`${certificateData.batch}${acadStr}`, c2X, metaBoxY + 59);

        // 5. Formal Certification Statement
        const certParaY = 260;
        doc
          .font('Helvetica')
          .fontSize(8.5)
          .fillColor('#334155')
          .text(
            'This is to officially certify that the student named above has satisfactorily cleared all institutional liabilities, returned all library books & laboratory assets, settled all financial/mess fees, and obtained approval from all requisite departments.',
            45,
            certParaY,
            {
              width: pageW - 90,
              align: 'center',
              lineGap: 2.5
            }
          );

        // 6. Itemized Clearance Departments Table (Unified Container with Soft Corners)
        const tableY = 296;
        const tableX = 45;
        const tableW = pageW - 90;

        // Exclude any department configured as Optional / Exempt or Inactive
        const exemptDepts = await prisma.clearanceDepartment.findMany({
          where: {
            OR: [
              { requiresClearance: false },
              { isActive: false }
            ]
          },
          select: { code: true }
        });
        const exemptCodes = new Set(exemptDepts.map((d) => d.code));

        let clearanceRows: ClearanceItemPdf[] = [];

        if (certificateData.clearances && certificateData.clearances.length > 0) {
          clearanceRows = certificateData.clearances.filter(
            (c: any) =>
              c.status !== 'NOT_APPLICABLE' &&
              c.requiresClearance !== false &&
              !exemptCodes.has(c.departmentCode)
          );
        } else {
          // Dynamically query authoritative active departments that REQUIRE clearance
          const activeDepts = await prisma.clearanceDepartment.findMany({
            where: {
              isActive: true,
              requiresClearance: true,
              isAcademicBranch: false
            },
            orderBy: { displayOrder: 'asc' }
          });

          clearanceRows = [
            ...activeDepts.map((d) => ({
              departmentName: d.name,
              departmentCode: d.code,
              status: 'CLEARED',
              approvalTimestamp: certificateData.issuedAt
            })),
            {
              departmentName: `Academic Branch (${certificateData.departmentName})`,
              departmentCode: 'ACAD',
              status: 'CLEARED',
              approvalTimestamp: certificateData.issuedAt
            }
          ];
        }

        // Guarantee that any separate laboratories are unified into exactly ONE "Laboratory" entry
        const isLabItem = (item: ClearanceItemPdf) => {
          const code = (item.departmentCode || '').toUpperCase().trim();
          const name = (item.departmentName || '').toLowerCase().trim();
          return ['PHY', 'CHEM', 'LAB', 'PHY_LAB', 'CHEM_LAB'].includes(code) ||
                 name === 'laboratory' ||
                 (name.includes('laboratory') && !name.includes('academic') && !name.includes('branch'));
        };

        const labItems = clearanceRows.filter(isLabItem);
        if (labItems.length > 0) {
          const nonLabItems = clearanceRows.filter((item) => !isLabItem(item));
          let latestLabTimestamp: Date | string = certificateData.issuedAt;
          for (const l of labItems) {
            if (l.approvalTimestamp && new Date(l.approvalTimestamp) > new Date(latestLabTimestamp)) {
              latestLabTimestamp = l.approvalTimestamp;
            }
          }

          const unifiedLabItem: ClearanceItemPdf = {
            departmentName: 'Laboratory',
            departmentCode: 'LAB',
            status: 'CLEARED',
            approvalTimestamp: latestLabTimestamp,
            reviewedByName: 'Designated Laboratory In-charge'
          };

          // Re-insert Laboratory at standard position (display order 2, right after LIB)
          const merged: ClearanceItemPdf[] = [];
          let labAdded = false;
          for (const item of nonLabItems) {
            const cCode = (item.departmentCode || '').toUpperCase();
            if (!labAdded && (cCode === 'HST' || cCode === 'SPT' || cCode === 'ACC' || cCode === 'ACAD')) {
              merged.push(unifiedLabItem);
              labAdded = true;
            }
            merged.push(item);
          }
          if (!labAdded) merged.push(unifiedLabItem);
          clearanceRows = merged;
        }

        const headerHeight = 22;
        const rowHeight = 24;
        const totalTableH = headerHeight + (clearanceRows.length * rowHeight);

        // Single Outer Table Box Container (Soft 8px Rounded Corners)
        doc
          .roundedRect(tableX, tableY, tableW, totalTableH, 8)
          .fillAndStroke('#ffffff', '#cbd5e1');

        // Table Header Background (Top rounded corners)
        doc
          .save()
          .roundedRect(tableX, tableY, tableW, totalTableH, 8)
          .clip();

        doc
          .rect(tableX, tableY, tableW, headerHeight)
          .fill('#1e3a8a');

        doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff');
        doc.text('#', tableX + 10, tableY + 7, { width: 18 });
        doc.text('CLEARANCE DEPARTMENT / SECTION', tableX + 32, tableY + 7, { width: 200 });
        doc.text('CODE', tableX + 240, tableY + 7, { width: 45 });
        doc.text('STATUS', tableX + 290, tableY + 7, { width: 75 });
        doc.text('APPROVAL TIMESTAMP', tableX + 375, tableY + 7, { width: 120 });

        let rowY = tableY + headerHeight;

        clearanceRows.forEach((item, index) => {
          const isEven = index % 2 === 0;
          const bgFill = isEven ? '#ffffff' : '#f8fafc';

          // Horizontal row separator line
          if (index > 0) {
            doc
              .moveTo(tableX, rowY)
              .lineTo(tableX + tableW, rowY)
              .lineWidth(0.5)
              .strokeColor('#e2e8f0')
              .stroke();
          }

          // Row Background Fill
          doc
            .rect(tableX, rowY, tableW, rowHeight)
            .fill(bgFill);

          // #
          doc.font('Helvetica').fontSize(8).fillColor('#64748b').text(String(index + 1), tableX + 10, rowY + 7);

          // Department Name
          doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#0f172a').text(item.departmentName, tableX + 32, rowY + 7, { width: 200, ellipsis: true });

          // Department Code
          doc.font('Helvetica-Bold').fontSize(8).fillColor('#1e3a8a').text(item.departmentCode || 'DEPT', tableX + 240, rowY + 7);

          // Refined Status Badge
          const isDue = item.status === 'DUE';
          const isHold = item.status === 'ON_HOLD';

          let badgeBg = '#ecfdf5';
          let badgeBorder = '#a7f3d0';
          let badgeTextColor = '#047857';
          let badgeLabel = 'NO DUES';

          if (isDue) {
            badgeBg = '#fef2f2';
            badgeBorder = '#fca5a5';
            badgeTextColor = '#b91c1c';
            badgeLabel = 'DUE';
          } else if (isHold) {
            badgeBg = '#fffbeb';
            badgeBorder = '#fde68a';
            badgeTextColor = '#b45309';
            badgeLabel = 'ON HOLD';
          }

          // Subtle rounded badge (4px radius)
          doc
            .roundedRect(tableX + 290, rowY + 4.5, 62, 15, 4)
            .lineWidth(0.75)
            .fillAndStroke(badgeBg, badgeBorder);

          doc
            .font('Helvetica-Bold')
            .fontSize(7.5)
            .fillColor(badgeTextColor)
            .text(badgeLabel, tableX + 290, rowY + 7.5, { width: 62, align: 'center' });

          // Exact Approval Timestamp
          const tsDate = item.approvalTimestamp ? new Date(item.approvalTimestamp) : new Date(certificateData.issuedAt);
          const formattedTimestamp = `${tsDate.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })} ${tsDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })}`;

          doc.font('Helvetica').fontSize(8).fillColor('#334155').text(formattedTimestamp, tableX + 375, rowY + 7, { width: 120 });

          rowY += rowHeight;
        });

        doc.restore();

        // 7. Respective Department HOD Signature Line
        const footerY = Math.max(rowY + 36, 680);

        const hodSigX = pageW - 235;
        const hodSigW = 190;
        doc
          .moveTo(hodSigX, footerY + 24)
          .lineTo(hodSigX + hodSigW, footerY + 24)
          .lineWidth(1)
          .strokeColor('#475569')
          .stroke();

        const hodDisplayName = certificateData.hodName && certificateData.hodName.trim() !== ''
          ? certificateData.hodName
          : 'Head of the Department';

        doc
          .font('Helvetica-Bold')
          .fontSize(10.5)
          .fillColor('#0f172a')
          .text(hodDisplayName, hodSigX, footerY + 28, { width: hodSigW, align: 'center' });

        doc
          .font('Helvetica')
          .fontSize(8.5)
          .fillColor('#64748b')
          .text(`Head of the Department`, hodSigX, footerY + 41, { width: hodSigW, align: 'center' });

        doc
          .font('Helvetica')
          .fontSize(8)
          .fillColor('#64748b')
          .text(`Dept. of ${certificateData.departmentName}`, hodSigX, footerY + 52, { width: hodSigW, align: 'center', ellipsis: true });

        doc.end();

        stream.on('finish', () => {
          resolve(outputPath);
        });

        stream.on('error', (err) => {
          reject(err);
        });
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generates a clean, simple official PDF report for Cleared students of a department
   * with Officer Signature and Summary Metrics.
   */
  public static async generateClearedReportPdf(
    reportData: {
      departmentName: string;
      departmentCode: string;
      officerName: string;
      officerEmployeeId?: string;
      totalCleared: number;
      students: Array<{
        sNo: number;
        fullName: string;
        usn: string;
        branch: string;
        remarks?: string;
        clearedAt: string;
      }>;
    },
    outputStream: any
  ): Promise<void> {
    return new Promise(async (resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 40,
          bufferPages: true
        });

        doc.pipe(outputStream);

        const pageW = doc.page.width; // 595.28
        const leftM = 40;
        const contentW = pageW - leftM * 2; // 515.28

        // Helper to draw standard header
        const drawHeader = (isFirstPage: boolean) => {
          if (isFirstPage) {
            const logoPath = path.resolve(process.cwd(), 'assets/mce_logo.png');
            const hasLogo = fs.existsSync(logoPath);
            if (hasLogo) {
              doc.image(logoPath, leftM, 38, { width: 42, height: 42 });
              doc
                .font('Helvetica-Bold')
                .fontSize(14)
                .fillColor('#1e3a8a')
                .text('MALNAD COLLEGE OF ENGINEERING', leftM + 50, 40);
              doc
                .font('Helvetica')
                .fontSize(8.5)
                .fillColor('#64748b')
                .text('Hassan - 573202, Karnataka | Autonomous Institution Affiliated to VTU', leftM + 50, 56);
              doc
                .font('Helvetica')
                .fontSize(8)
                .fillColor('#94a3b8')
                .text('Official Departmental Clearance & Dues Settlement Record', leftM + 50, 68);
            } else {
              doc
                .font('Helvetica-Bold')
                .fontSize(14)
                .fillColor('#1e3a8a')
                .text('MALNAD COLLEGE OF ENGINEERING', leftM, 40, { align: 'center', width: contentW });
              doc
                .font('Helvetica')
                .fontSize(8.5)
                .fillColor('#64748b')
                .text('Hassan - 573202, Karnataka | Autonomous Institution Affiliated to VTU', leftM, 56, { align: 'center', width: contentW });
            }

            // Divider line
            doc.moveTo(leftM, 88).lineTo(leftM + contentW, 88).lineWidth(1).strokeColor('#cbd5e1').stroke();

            // Report Title Banner
            doc
              .font('Helvetica-Bold')
              .fontSize(12)
              .fillColor('#0f172a')
              .text(`${reportData.departmentName.toUpperCase()} — CLEARED STUDENTS REPORT`, leftM, 98, {
                align: 'center',
                width: contentW
              });

            // Metadata summary card
            doc
              .roundedRect(leftM, 118, contentW, 46, 6)
              .fillAndStroke('#f8fafc', '#e2e8f0');

            doc
              .font('Helvetica-Bold')
              .fontSize(8.5)
              .fillColor('#334155')
              .text('Department:', leftM + 12, 126);
            doc
              .font('Helvetica')
              .fontSize(8.5)
              .fillColor('#0f172a')
              .text(`${reportData.departmentName} (${reportData.departmentCode})`, leftM + 75, 126);

            doc
              .font('Helvetica-Bold')
              .fontSize(8.5)
              .fillColor('#334155')
              .text('Generated On:', leftM + 12, 142);
            doc
              .font('Helvetica')
              .fontSize(8.5)
              .fillColor('#0f172a')
              .text(new Date().toLocaleString(), leftM + 75, 142);

            doc
              .font('Helvetica-Bold')
              .fontSize(8.5)
              .fillColor('#334155')
              .text('Authorized Officer:', leftM + 290, 126);
            doc
              .font('Helvetica')
              .fontSize(8.5)
              .fillColor('#0f172a')
              .text(
                `${reportData.officerName}${reportData.officerEmployeeId ? ' (' + reportData.officerEmployeeId + ')' : ''}`,
                leftM + 375,
                126,
                { width: 130, ellipsis: true }
              );

            doc
              .font('Helvetica-Bold')
              .fontSize(8.5)
              .fillColor('#334155')
              .text('Cleared Students:', leftM + 290, 142);
            doc
              .font('Helvetica-Bold')
              .fontSize(8.5)
              .fillColor('#16a34a')
              .text(`${reportData.totalCleared} Students`, leftM + 375, 142);
          }
        };

        const drawTableHeader = (startY: number) => {
          doc.rect(leftM, startY, contentW, 20).fill('#f1f5f9');
          doc.rect(leftM, startY, contentW, 20).strokeColor('#cbd5e1').lineWidth(0.5).stroke();

          doc.font('Helvetica-Bold').fontSize(8).fillColor('#475569');
          doc.text('#', leftM + 6, startY + 6, { width: 25 });
          doc.text('STUDENT NAME', leftM + 35, startY + 6, { width: 200 });
          doc.text('USN', leftM + 240, startY + 6, { width: 120 });
          doc.text('BRANCH', leftM + 365, startY + 6, { width: 65 });
          doc.text('CLEARANCE DATE', leftM + 435, startY + 6, { width: 80 });
        };

        drawHeader(true);

        let currentY = 176;
        drawTableHeader(currentY);
        currentY += 20;

        // Table Rows
        reportData.students.forEach((s) => {
          if (currentY + 22 > 730) {
            doc.addPage({ size: 'A4', margin: 40 });
            drawHeader(false);
            currentY = 40;
            drawTableHeader(currentY);
            currentY += 20;
          }

          doc.rect(leftM, currentY, contentW, 20).strokeColor('#f1f5f9').lineWidth(0.5).stroke();

          doc.font('Helvetica').fontSize(8).fillColor('#64748b').text(String(s.sNo), leftM + 6, currentY + 6, { width: 25 });
          doc.font('Helvetica-Bold').fontSize(8).fillColor('#0f172a').text(s.fullName, leftM + 35, currentY + 6, { width: 200, ellipsis: true });
          doc.font('Helvetica-Bold').fontSize(8).fillColor('#1d4ed8').text(s.usn, leftM + 240, currentY + 6, { width: 120 });
          doc.font('Helvetica').fontSize(8).fillColor('#475569').text(s.branch, leftM + 365, currentY + 6, { width: 65 });
          doc.font('Helvetica').fontSize(7.5).fillColor('#64748b').text(s.clearedAt, leftM + 435, currentY + 6, { width: 80 });

          currentY += 20;
        });

        // Ensure room for signature block
        if (currentY + 80 > 760) {
          doc.addPage({ size: 'A4', margin: 40 });
          currentY = 40;
        }

        const sigY = Math.max(currentY + 35, 710);

        // Signature block on right
        doc.moveTo(leftM + 310, sigY + 15).lineTo(leftM + contentW, sigY + 15).lineWidth(1).strokeColor('#0f172a').stroke();

        doc
          .font('Helvetica-Bold')
          .fontSize(9)
          .fillColor('#0f172a')
          .text('Authorized Officer Signature', leftM + 310, sigY + 20, { width: 200, align: 'right' });

        doc
          .font('Helvetica')
          .fontSize(8.5)
          .fillColor('#334155')
          .text(reportData.officerName, leftM + 310, sigY + 32, { width: 200, align: 'right' });

        doc
          .font('Helvetica')
          .fontSize(8)
          .fillColor('#64748b')
          .text(`${reportData.departmentName}`, leftM + 310, sigY + 43, { width: 200, align: 'right' });

        doc
          .font('Helvetica')
          .fontSize(7.5)
          .fillColor('#64748b')
          .text('Malnad College of Engineering, Hassan', leftM + 310, sigY + 53, { width: 200, align: 'right' });

        doc.end();
        resolve();
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generates official Physical Certificate Submission Report PDF with Date Range filters
   * for College Office / Administrative Section.
   */
  public static async generateSubmissionReportPdf(
    reportData: {
      collegeOfficeName: string;
      officerName: string;
      officerEmployeeId?: string;
      dateRangeLabel: string;
      statusFilterLabel: string;
      totalCertificates: number;
      totalSubmitted: number;
      totalNotSubmitted: number;
      submissionRate: number;
      records: Array<{
        sNo: number;
        fullName: string;
        usn: string;
        branch: string;
        certificateNumber: string;
        issuedAt: string;
        isSubmitted: boolean;
        submittedAt?: string;
        submissionRemarks?: string;
      }>;
    },
    outputStream: any
  ): Promise<void> {
    return new Promise(async (resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 36,
          bufferPages: true
        });

        doc.pipe(outputStream);

        const pageW = doc.page.width; // 595.28
        const leftM = 36;
        const contentW = pageW - leftM * 2; // 523.28

        const drawHeader = (isFirstPage: boolean) => {
          if (isFirstPage) {
            const logoPath = path.resolve(process.cwd(), 'assets/mce_logo.png');
            const hasLogo = fs.existsSync(logoPath);
            if (hasLogo) {
              doc.image(logoPath, leftM, 32, { width: 44, height: 44 });
              doc
                .font('Helvetica-Bold')
                .fontSize(14)
                .fillColor('#1e3a8a')
                .text('MALNAD COLLEGE OF ENGINEERING', leftM + 52, 34);
              doc
                .font('Helvetica-Bold')
                .fontSize(8)
                .fillColor('#475569')
                .text('Autonomous Institution Affiliated to VTU, Belagavi | Approved by AICTE, New Delhi', leftM + 52, 51);
              doc
                .font('Helvetica')
                .fontSize(7.5)
                .fillColor('#64748b')
                .text('College Office / Administrative Section | Hassan, Karnataka - 573202', leftM + 52, 63);
            } else {
              doc
                .font('Helvetica-Bold')
                .fontSize(15)
                .fillColor('#1e3a8a')
                .text('MALNAD COLLEGE OF ENGINEERING', leftM, 34, { width: contentW, align: 'center' });
              doc
                .font('Helvetica')
                .fontSize(8)
                .fillColor('#64748b')
                .text('College Office / Administrative Section | Hassan, Karnataka - 573202', leftM, 52, { width: contentW, align: 'center' });
            }

            // Divider Line
            doc.moveTo(leftM, 84).lineTo(leftM + contentW, 84).lineWidth(1.5).strokeColor('#1e3a8a').stroke();
            doc.moveTo(leftM, 87).lineTo(leftM + contentW, 87).lineWidth(0.5).strokeColor('#d97706').stroke();

            // Title Banner
            doc.roundedRect(leftM, 96, contentW, 28, 6).fillAndStroke('#eff6ff', '#bfdbfe');
            doc
              .font('Helvetica-Bold')
              .fontSize(10.5)
              .fillColor('#1e3a8a')
              .text('PHYSICAL NO DUE CERTIFICATE SUBMISSION REGISTRY REPORT', leftM, 104, { width: contentW, align: 'center' });

            // Date Range & Metadata Sub-bar
            const nowStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
            doc
              .font('Helvetica')
              .fontSize(8)
              .fillColor('#334155')
              .text(`Reporting Period: ${reportData.dateRangeLabel}`, leftM + 6, 130);
            doc
              .font('Helvetica')
              .fontSize(8)
              .fillColor('#334155')
              .text(`Filter: ${reportData.statusFilterLabel}  |  Generated: ${nowStr}`, leftM, 130, { width: contentW - 6, align: 'right' });

            // Metric Summary Cards Row
            const cardW = (contentW - 18) / 4;
            const cardY = 144;
            const cardH = 38;

            const cards = [
              { label: 'Total Issued', value: String(reportData.totalCertificates), bg: '#f8fafc', stroke: '#e2e8f0', color: '#1e293b' },
              { label: 'Physically Submitted', value: String(reportData.totalSubmitted), bg: '#f0fdf4', stroke: '#bbf7d0', color: '#15803d' },
              { label: 'Pending Submission', value: String(reportData.totalNotSubmitted), bg: '#fffbeb', stroke: '#fde68a', color: '#b45309' },
              { label: 'Submission Rate', value: `${reportData.submissionRate}%`, bg: '#eff6ff', stroke: '#bfdbfe', color: '#1d4ed8' }
            ];

            cards.forEach((c, idx) => {
              const cx = leftM + idx * (cardW + 6);
              doc.roundedRect(cx, cardY, cardW, cardH, 5).fillAndStroke(c.bg, c.stroke);
              doc.font('Helvetica-Bold').fontSize(13).fillColor(c.color).text(c.value, cx + 8, cardY + 7);
              doc.font('Helvetica').fontSize(7.5).fillColor('#64748b').text(c.label, cx + 8, cardY + 23);
            });
          }
        };

        const drawTableHeader = (y: number) => {
          doc.rect(leftM, y, contentW, 20).fill('#1e3a8a');
          doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#ffffff');
          doc.text('#', leftM + 5, y + 6, { width: 20 });
          doc.text('STUDENT NAME', leftM + 28, y + 6, { width: 125 });
          doc.text('USN', leftM + 158, y + 6, { width: 75 });
          doc.text('BRANCH', leftM + 236, y + 6, { width: 45 });
          doc.text('CERTIFICATE NO', leftM + 284, y + 6, { width: 110 });
          doc.text('ISSUED DATE', leftM + 397, y + 6, { width: 55 });
          doc.text('PHYSICAL STATUS', leftM + 455, y + 6, { width: 65, align: 'center' });
        };

        drawHeader(true);

        let currentY = 192;
        drawTableHeader(currentY);
        currentY += 20;

        reportData.records.forEach((r, idx) => {
          // Check page overflow
          if (currentY + 22 > 770) {
            doc.addPage({ size: 'A4', margin: 36 });
            currentY = 36;
            drawTableHeader(currentY);
            currentY += 20;
          }

          const isEven = idx % 2 === 0;
          doc.rect(leftM, currentY, contentW, 20).fill(isEven ? '#ffffff' : '#f8fafc');
          doc.rect(leftM, currentY, contentW, 20).strokeColor('#f1f5f9').lineWidth(0.5).stroke();

          // S.No
          doc.font('Helvetica').fontSize(7.5).fillColor('#64748b').text(String(r.sNo), leftM + 5, currentY + 6, { width: 20 });
          // Student Name
          doc.font('Helvetica-Bold').fontSize(8).fillColor('#0f172a').text(r.fullName, leftM + 28, currentY + 6, { width: 125, ellipsis: true });
          // USN
          doc.font('Helvetica-Bold').fontSize(8).fillColor('#1d4ed8').text(r.usn, leftM + 158, currentY + 6, { width: 75 });
          // Branch
          doc.font('Helvetica').fontSize(7.5).fillColor('#475569').text(r.branch, leftM + 236, currentY + 6, { width: 45 });
          // Certificate Number
          doc.font('Helvetica').fontSize(7.5).fillColor('#0f172a').text(r.certificateNumber, leftM + 284, currentY + 6, { width: 110, ellipsis: true });
          // Issued Date
          doc.font('Helvetica').fontSize(7.5).fillColor('#64748b').text(r.issuedAt, leftM + 397, currentY + 6, { width: 55 });

          // Submission Status Badge
          const badgeX = leftM + 455;
          const badgeW = 65;
          const badgeH = 13;
          const badgeY = currentY + 3.5;

          if (r.isSubmitted) {
            doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 3).fillAndStroke('#ecfdf5', '#a7f3d0');
            doc.font('Helvetica-Bold').fontSize(6.5).fillColor('#047857').text('SUBMITTED', badgeX, badgeY + 3.5, { width: badgeW, align: 'center' });
          } else {
            doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 3).fillAndStroke('#fffbeb', '#fde68a');
            doc.font('Helvetica-Bold').fontSize(6.5).fillColor('#b45309').text('PENDING', badgeX, badgeY + 3.5, { width: badgeW, align: 'center' });
          }

          currentY += 20;
        });

        if (reportData.records.length === 0) {
          doc.rect(leftM, currentY, contentW, 30).fill('#ffffff');
          doc.font('Helvetica').fontSize(8.5).fillColor('#64748b').text('No physical certificate records found matching the specified criteria and date range.', leftM, currentY + 10, { width: contentW, align: 'center' });
          currentY += 30;
        }

        // Room for signature block
        if (currentY + 80 > 770) {
          doc.addPage({ size: 'A4', margin: 36 });
          currentY = 36;
        }

        const sigY = Math.max(currentY + 35, 715);

        // Official Signature line
        doc.moveTo(leftM + contentW - 210, sigY + 15).lineTo(leftM + contentW, sigY + 15).lineWidth(1).strokeColor('#0f172a').stroke();
        doc
          .font('Helvetica-Bold')
          .fontSize(8.5)
          .fillColor('#0f172a')
          .text('College Office In-charge / Dean', leftM + contentW - 210, sigY + 20, { width: 210, align: 'right' });
        doc
          .font('Helvetica')
          .fontSize(8)
          .fillColor('#475569')
          .text(reportData.officerName || 'Administrative Office In-charge', leftM + contentW - 210, sigY + 32, { width: 210, align: 'right' });
        doc
          .font('Helvetica')
          .fontSize(7.5)
          .fillColor('#64748b')
          .text('College Office, Malnad College of Engineering, Hassan', leftM + contentW - 210, sigY + 43, { width: 210, align: 'right' });

        doc.end();
        resolve();
      } catch (err) {
        reject(err);
      }
    });
  }
}
